FIXME  Ignore compiler errors
Perhaps due to changes in Noetic

    Errors     << pilz_trajectory_generation:make [...]/logs/pilz_trajectory_generation/build.make.000.log
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp: In member function ‘void pilz_trajectory_generation::MoveGroupSequenceAction::executeSequenceCallbackPlanAndExecute(const MoveGroupSequenceGoalConstPtr&, pilz_msgs::MoveGroupSequenceResult&)’:
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:133:100: error: ‘static bool planning_scene::PlanningScene::isEmpty(const RobotState&)’ is deprecated: Use moveit/utils/message_checks.h instead [-Werror=deprecated-declarations]
      133 |       planning_scene::PlanningScene::isEmpty(goal->planning_options.planning_scene_diff.robot_state) ?
	  |                                                                                                    ^
    In file included from /opt/ros/noetic/include/moveit/planning_scene_monitor/planning_scene_monitor.h:43,
		     from /opt/ros/noetic/include/moveit/move_group/move_group_capability.h:40,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/include/pilz_trajectory_generation/move_group_sequence_action.h:23,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:39:
    [...]/moveit/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h:951:75: note: declared here
      951 |   [[deprecated("Use moveit/utils/message_checks.h instead")]] static bool isEmpty(const moveit_msgs::RobotState& msg);
	  |                                                                           ^~~~~~~
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:133:100: error: ‘static bool planning_scene::PlanningScene::isEmpty(const RobotState&)’ is deprecated: Use moveit/utils/message_checks.h instead [-Werror=deprecated-declarations]
      133 |       planning_scene::PlanningScene::isEmpty(goal->planning_options.planning_scene_diff.robot_state) ?
	  |                                                                                                    ^
    In file included from /opt/ros/noetic/include/moveit/planning_scene_monitor/planning_scene_monitor.h:43,
		     from /opt/ros/noetic/include/moveit/move_group/move_group_capability.h:40,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/include/pilz_trajectory_generation/move_group_sequence_action.h:23,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:39:
    [...]/moveit/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h:951:75: note: declared here
      951 |   [[deprecated("Use moveit/utils/message_checks.h instead")]] static bool isEmpty(const moveit_msgs::RobotState& msg);
	  |                                                                           ^~~~~~~
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp: In member function ‘void pilz_trajectory_generation::MoveGroupSequenceAction::executeMoveCallbackPlanOnly(const MoveGroupSequenceGoalConstPtr&, pilz_msgs::MoveGroupSequenceResult&)’:
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:179:89: error: ‘static bool planning_scene::PlanningScene::isEmpty(const PlanningScene&)’ is deprecated: Use moveit/utils/message_checks.h instead [-Werror=deprecated-declarations]
      179 |       (planning_scene::PlanningScene::isEmpty(goal->planning_options.planning_scene_diff)) ?
	  |                                                                                         ^
    In file included from /opt/ros/noetic/include/moveit/planning_scene_monitor/planning_scene_monitor.h:43,
		     from /opt/ros/noetic/include/moveit/move_group/move_group_capability.h:40,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/include/pilz_trajectory_generation/move_group_sequence_action.h:23,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:39:
    [...]/moveit/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h:943:75: note: declared here
      943 |   [[deprecated("Use moveit/utils/message_checks.h instead")]] static bool isEmpty(const moveit_msgs::PlanningScene& msg);
	  |                                                                           ^~~~~~~
    [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:179:89: error: ‘static bool planning_scene::PlanningScene::isEmpty(const PlanningScene&)’ is deprecated: Use moveit/utils/message_checks.h instead [-Werror=deprecated-declarations]
      179 |       (planning_scene::PlanningScene::isEmpty(goal->planning_options.planning_scene_diff)) ?
	  |                                                                                         ^
    In file included from /opt/ros/noetic/include/moveit/planning_scene_monitor/planning_scene_monitor.h:43,
		     from /opt/ros/noetic/include/moveit/move_group/move_group_capability.h:40,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/include/pilz_trajectory_generation/move_group_sequence_action.h:23,
		     from [...]/src/pilz_industrial_motion/pilz_trajectory_generation/src/move_group_sequence_action.cpp:39:
    [...]/moveit/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h:943:75: note: declared here
      943 |   [[deprecated("Use moveit/utils/message_checks.h instead")]] static bool isEmpty(const moveit_msgs::PlanningScene& msg);
	  |                                                                           ^~~~~~~
    cc1plus: all warnings being treated as errors